language: java
jdk: oraclejdk8
dist: trusty

script:
  - if mvn dependency:tree | grep -B3 "version selected from constraint"; then
      echo "Error. Have found versions that are selected from constraint, pin those so they won't change themselves.";
      exit 1;
    fi;
  - mvn -B clean verify -Dvaadin.productionMode -Dcom.vaadin.testbench.Parameters.testsInParallel=2 -Dvaadin.proKey=$VAADIN_PRO_KEY -Dsauce.user=$SAUCE_USER -Dsauce.sauceAccessKey=$SAUCE_ACCESSKEY -P$IT_PROFILE

#deploy:
#  - provider: script
#    script: ./.travis.deploy.sh
#    skip_cleanup: true
#    on:
#      branch: master

# Cache requires a master build
branches:
  only:
    - master

env:
  matrix:
    - IT_PROFILE=npm-it,!bower-it
    - IT_PROFILE=bower-it,!npm-it

cache:
  directories:
  - $HOME/.m2

before_cache:
  # remove all build artifacts
  - rm -rf $HOME/.m2/repository/com/vaadin/vaadin-app-layout-flow
